/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentLoginRouteImport } from './routes/student-login'
import { Route as ExamResultsRouteImport } from './routes/exam-results'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateExamRouteImport } from './routes/create-exam'
import { Route as IndexRouteImport } from './routes/index'

const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student-login',
  path: '/student-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamResultsRoute = ExamResultsRouteImport.update({
  id: '/exam-results',
  path: '/exam-results',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateExamRoute = CreateExamRouteImport.update({
  id: '/create-exam',
  path: '/create-exam',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-exam': typeof CreateExamRoute
  '/dashboard': typeof DashboardRoute
  '/exam': typeof ExamRoute
  '/exam-results': typeof ExamResultsRoute
  '/student-login': typeof StudentLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-exam': typeof CreateExamRoute
  '/dashboard': typeof DashboardRoute
  '/exam': typeof ExamRoute
  '/exam-results': typeof ExamResultsRoute
  '/student-login': typeof StudentLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-exam': typeof CreateExamRoute
  '/dashboard': typeof DashboardRoute
  '/exam': typeof ExamRoute
  '/exam-results': typeof ExamResultsRoute
  '/student-login': typeof StudentLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-exam'
    | '/dashboard'
    | '/exam'
    | '/exam-results'
    | '/student-login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-exam'
    | '/dashboard'
    | '/exam'
    | '/exam-results'
    | '/student-login'
  id:
    | '__root__'
    | '/'
    | '/create-exam'
    | '/dashboard'
    | '/exam'
    | '/exam-results'
    | '/student-login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateExamRoute: typeof CreateExamRoute
  DashboardRoute: typeof DashboardRoute
  ExamRoute: typeof ExamRoute
  ExamResultsRoute: typeof ExamResultsRoute
  StudentLoginRoute: typeof StudentLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-login': {
      id: '/student-login'
      path: '/student-login'
      fullPath: '/student-login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-results': {
      id: '/exam-results'
      path: '/exam-results'
      fullPath: '/exam-results'
      preLoaderRoute: typeof ExamResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-exam': {
      id: '/create-exam'
      path: '/create-exam'
      fullPath: '/create-exam'
      preLoaderRoute: typeof CreateExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateExamRoute: CreateExamRoute,
  DashboardRoute: DashboardRoute,
  ExamRoute: ExamRoute,
  ExamResultsRoute: ExamResultsRoute,
  StudentLoginRoute: StudentLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
